## 任务描述

1. 掌握Numpy的分割

## 相关知识

**创建数据**

首先 import 模块

In [1]:
import numpy as np

建立3行4列的Array

In [2]:
A = np.arange(12).reshape((3, 4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**纵向分割**

In [3]:
print(np.split(A, 2, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


**横向分割** 

In [4]:
print(np.split(A, 3, axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


**错误的分割**  

范例的Array只有4列，只能等量对分，因此输入以上程序代码后Python就会报错。

In [5]:
print(np.split(A, 3, axis=1))

ValueError: array split does not result in an equal division

为了解决这种情况, 我们会有下面这种方式.

**不等量的分割 np.array_split()** 

在机器学习时经常会需要将数据做不等量的分割，因此解决办法为`np.array_split()`

In [6]:
print(np.array_split(A, 3, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


成功将Array不等量分割!

## 编程要求

根据Numpy分割方法，完成以下任务

1. 随机创建5行6列的矩阵，数值范围在50-100之间

2. 将其分割成纵向分割成3个矩阵

3. 将其分割成纵向分割成4个矩阵

### 参考答案

In [7]:
import numpy as np
a=np.random.randint(50,100,(5,6))
print(a)
print(np.split(a, 3, axis=1))
print(np.array_split(a, 4, axis=1))

[[52 59 60 83 69 78]
 [61 75 82 66 91 65]
 [55 73 61 95 88 73]
 [76 75 75 71 57 72]
 [77 73 72 72 86 75]]
[array([[52, 59],
       [61, 75],
       [55, 73],
       [76, 75],
       [77, 73]]), array([[60, 83],
       [82, 66],
       [61, 95],
       [75, 71],
       [72, 72]]), array([[69, 78],
       [91, 65],
       [88, 73],
       [57, 72],
       [86, 75]])]
[array([[52, 59],
       [61, 75],
       [55, 73],
       [76, 75],
       [77, 73]]), array([[60, 83],
       [82, 66],
       [61, 95],
       [75, 71],
       [72, 72]]), array([[69],
       [91],
       [88],
       [57],
       [86]]), array([[78],
       [65],
       [73],
       [72],
       [75]])]
