## 任务描述

1.掌握Numpy数组基本运算；

2.掌握Numpy矩阵基本运算。

## 相关知识

**数组加减乘除**

In [1]:
import numpy as np

In [2]:
a = np.array( [20,30,40,50] )
b = np.arange(2,6)

通过上一节的学习，我们应该知道b的数组究竟是什么样的，打印出来看看吧

In [3]:
print(b)

[2 3 4 5]


In [4]:
c=a+b
print(c)

[22 33 44 55]


In [5]:
c=a-b
print(c)

[18 27 36 45]


In [6]:
c=a*b
print(c)

[ 40  90 160 250]


In [7]:
c=a/b
print(c)

[10. 10. 10. 10.]


**乘方**

有所不同的是，在Numpy中，想要求出矩阵中各个元素的乘方需要依赖双星符号  **

In [8]:
c=b**2 
print(c)

[ 4  9 16 25]


**逻辑判断**

在脚本中对print函数进行一些修改可以进行逻辑判断：

In [9]:
print(b)
print(b<3)

[2 3 4 5]
[ True False False False]


**数学函数**

Numpy中具有很多的数学函数工具，比如三角函数等，当我们需要对矩阵中每一项元素进行函数运算时，可以很简便的调用它们

**sin()函数**

In [10]:
c=10*np.sin(a)
print(c)

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


**sum(), min(), max()函数**

In [11]:
a=np.random.random((2,4))  #random()随机生成数字，
print(a)

[[0.22795901 0.11353207 0.50069315 0.40661031]
 [0.63671835 0.0974037  0.01259336 0.65392103]]


In [12]:
print('总和sum为：',np.sum(a))
print('最小值min为：',np.min(a))
print('最大值max为：',np.max(a))

总和sum为： 2.64943098067479
最小值min为： 0.012593358784842024
最大值max为： 0.6539210279076999


**注意：**由于random()函数的随机性，所以每一次运行出来的结果可能不一样哦。

**argmin()和argmax()索引元素**

In [13]:
A = np.arange(2,14).reshape((3,4))   

print(A)
print('最小值索引值为：',np.argmin(A))   
print('最大值索引值为：',np.argmax(A)) 

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
最小值索引值为： 0
最大值索引值为： 11


其中的 argmin()和 argmax()两个函数分别对应着求矩阵中最小元素和最大元素的索引。相应的，在矩阵的12个元素中，最小值即2，对应索引0，最大值为13，对应索引为11。

**mean()和average()函数求均值**

如果需要计算统计中的均值，可以利用下面的方式，将整个矩阵的均值求出来：

In [14]:
print(np.mean(A))       
print(np.average(A))   

7.5
7.5


**排序函数sort()**

同样的，我们可以对所有元素进行仿照列表一样的排序操作，但这里的排序函数仍然仅针对每一行进行从小到大排序操作：

In [15]:
A = np.arange(14,2, -1).reshape((3,4)) 

print('排序前的A：\n',A)  

print('排序后的A:\n',np.sort(A))    

排序前的A：
 [[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
排序后的A:
 [[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


**Numpy中的乘法运算符 * 指示按元素计算，矩阵乘法可以使用dot函数**

接下来我们通过两个例子进行对比：

**一维矩阵**

In [16]:
a=np.array([2,3,4])
b=np.array([1,2,4])
print(a*b)
print(np.dot(a,b))

[ 2  6 16]
24


**a * b 计算示意图**

![jupyter](https://i.loli.net/2021/05/11/ms1DAfLlJvZaXHw.png)

**dot(a ,b)计算示意图**

![jupyter](https://i.loli.net/2021/05/11/NitK7xXFkepVbYC.png)

**二维矩阵** 

In [17]:
a=np.array([[0,2,3,1],[3,7,7,4]])
b=np.array([[12,5],[12,7],[15,4],[12,6]])
print(a)
print(b)

[[0 2 3 1]
 [3 7 7 4]]
[[12  5]
 [12  7]
 [15  4]
 [12  6]]


In [18]:
print（a*b）

SyntaxError: invalid character in identifier (<ipython-input-18-41aa41fb6325>, line 1)

可以发现由于矩阵行列不相同，在使用按元素计算的时候就会报错。

In [19]:
print(np.dot(a,b))

[[ 81  32]
 [273 116]]


![jupyter](https://i.loli.net/2021/05/11/fTj5AtQEl7awnsZ.png)

**矩阵的转置**

有两种表示方法：

In [20]:
A = np.arange(14,2, -1).reshape((3,4))

print(np.transpose(A))  

print(A.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


## 编程要求

根据Numpy的基本使用方法，按照一下步骤完成任务。

1. 随机生成一个3行4列和4行3列的矩阵，其数值范围在1-10之间

2. 使用dot函数进行矩阵乘法

3. 在结果中找出最大值和最小值以及它们各自的索引

### 参考答案

In [21]:
import numpy as np
a=np.random.randint(1,10,(3,4))
b=np.random.randint(1,10,(4,3))
c=np.dot(a,b)
print(c)
print("最小值为：",np.min(c))
print("最大值为：",np.max(c))
print("最小值索引为：",np.argmin(c))
print("最大值索引为：",np.argmax(c))

[[155 136  93]
 [118  87  74]
 [181 174 135]]
最小值为： 74
最大值为： 181
最小值索引为： 5
最大值索引为： 6
