## 任务描述

1. 了解Numpy的对象属性；

2. 掌握Numpy创建数组array的基本操作。

## 相关知识

**Numpy-简介**

Numpy 是一个 Python 包。 它代表 “Numeric Python”。 它是一个由多维数组对象和用于处理数组的例程集合组成的库。

**Numpy - ndarray 对象**

Numpy的数组类被称作ndarray。通常被称作数组。注意numpy.array和标准Python库类array.array并不相同，后者只处理一维数组和提供少量功能。


**ndarray对象属性：**

ndarray.ndim    数组的维度

ndarray.shape   行数与列数。 例如一个2行3列的矩阵，它的shape属性将是(2,3)。

ndarray.size    数组元素的总个数，等于shape属性中元组元素的乘积。

ndarray.dtype   数组的所需数据类型

**实例1：**

首先我们先导入模块

In [1]:
import numpy as np  #为了方便使用numpy 采用np简写

In [2]:
#列表转化为矩阵： 
array = np.array([[1,2,3],[2,3,4]]) 
print(array) 

[[1 2 3]
 [2 3 4]]


接着我们看看这几种属性的结果:

In [3]:
print('number of dim:',array.ndim)  # 维度

number of dim: 2


In [4]:
print('shape :',array.shape)    # 行数和列数

shape : (2, 3)


In [5]:
print('size:',array.size)   # 元素个数

size: 6


In [6]:
print('type:',array.dtype) 

type: int32


**创建Array**

再介绍完Numpy的对象属性之后，我们就来创建array

**实例2：创建指定数据dtype的数组array**

In [7]:
a = np.array([2,23,4],dtype=np.int32)
print(a.dtype)

int32


**实例3：创建全零数组zeros**

In [8]:
b = np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**实例4：创建全一数组ones**

In [9]:
c = np.ones((3,4),dtype = int) 
print(c)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


**实例5：创建全空数组empty**

In [10]:
d = np.empty((3,4)) # 数据为empty，3行4列，其实每个值都是接近于零的数
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**实例6：用arange创建连续数组**

In [11]:
e = np.arange(10,20,2) # 10-19 的数据，2步长
print(e)

[10 12 14 16 18]


**实例7：使用reshape改变数据的形状**

In [12]:
f = np.arange(12).reshape((3,4))  
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**实例8：用linspace创建线段型数据**

In [13]:
a = np.linspace(1,10,20)    # 开始端1，结束端10，且分割成20个数据，生成线段
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


同样也能进行 reshape 工作:

In [14]:
a = np.linspace(1,10,20).reshape((5,4)) # 更改shape
print(a)

[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


## 编程要求

复习以上知识，使用Numpy创建一个三维数组，具体要求如下：

1.数组长度为45

2.shape为(3,3,5)

**赶紧实战吧！**

### 参考答案

In [16]:
import numpy as np
array=np.arange(45).reshape((3,3,5))
print(array)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]
