## 任务描述

1. 掌握Numpy的索引方法

## 相关知识

### 一维索引 

在元素列表或者数组中，我们可以用如同 a[2] 一样的表示方法，同样的，在Numpy中也有相对应的表示方法：

In [1]:
import numpy as np
A = np.arange(3,15)
         
print(A)  

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [2]:
print(A[3]) 

6


让我们将矩阵转换为二维的，此时进行同样的操作：

In [3]:
A = np.arange(3,15).reshape((3,4))

print(A)      

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [4]:
print(A[2])         

[11 12 13 14]


实际上这时的A[2]对应的就是矩阵A中第三行(从0开始算第一行)的所有元素。

### 二维索引 

如果你想要表示**具体的单个元素**，可以仿照上述的例子：

In [5]:
print(A[1][1])     
print(A[1, 1])     

8
8


在Python的 list 中，我们可以利用 : 对一定范围内的元素进行**切片操作**，在Numpy中我们依然可以给出相应的方法：

In [6]:
print(A[1, 1:3])   

[8 9]


这一表示形式即针对第二行中第2到第4列元素进行切片输出（不包含第4列）。 此时我们适当的利用for函数进行打印：

In [7]:
for row in A:
    print(row)


[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


此时它会逐行进行打印操作。如果想进行逐列打印，就需要稍稍变化一下：

In [8]:
for column in A.T:
    print(column)


[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


上述表示方法即对A进行转置，再将得到的矩阵逐行输出即可得到原矩阵的逐列输出。

## 编程要求

根据Numpy的索引方法，按照一下步骤完成任务。

1. 随机生成一个7行8列矩阵，数值范围在1-500之间

2. 完成单元素第五行第三个元素的搜索打印

3. 完成第二行和第四行的转置切片输出


In [9]:
import numpy as np
a=np.random.randint(1,500,(7,8))
print("原数组a:\n",a)
print("单元素索引为：",a[4,2])
print("转置切片为：\n",a[1:3, :].T) 

原数组a:
 [[394  23 489 349 225 167  57  75]
 [427 371 253 144  98 193 124 258]
 [379 396 486  56 264 164 462 286]
 [229 307 339 100 348 294 260 214]
 [261 282 376 472 222 471 314 296]
 [336 312 134 135  99 359  20 130]
 [464 377 107 449 110 289  99  80]]
单元素索引为： 376
转置切片为：
 [[427 379]
 [371 396]
 [253 486]
 [144  56]
 [ 98 264]
 [193 164]
 [124 462]
 [258 286]]
