## 任务描述

1. 通过电影分类实战演练进一步熟悉kNN算法步骤

2. 了解np.tile()函数基本用法

## 相关知识

**kNN算法步骤如下**

1.计算已知类别数据集中的点与当前预测点之间的距离；

2.按照距离递增次序排序；

3.选取与当前点距离最小的k个点；

4.确定前k个点所在类别的出现频率；

5.返回前k个点所出现频率最高的类别作为当前点的预测分类。

**np.tile()函数**

**沿X轴复制**

在numpy中，np.tile（a,(2)）函数的作用就是将函数将函数沿着X轴扩大两倍（tile有“平铺”的意思）。如果扩大倍数只有一个，默认为X轴

In [1]:
import numpy as np
a = np.array(
    [
        [1,2,3],
        [3,4,5],
        [6,7,8]
    ]
)
print(np.tile(a,2))

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]]


**XY轴都复制，或只沿着Y轴复制的方法**

np.tile(a,(2,1))第一个参数为Y轴扩大倍数，第二个为X轴扩大倍数。本例中X轴扩大一倍便为不复制。

In [2]:
print(np.tile(a,(2,1)))

[[1 2 3]
 [3 4 5]
 [6 7 8]
 [1 2 3]
 [3 4 5]
 [6 7 8]]


**案例实战**

**使用k-近邻算法分类一个电影是爱情片还是动作片**

以下就是已有的数据集合，也就是训练样本集。这个数据集有两个特征，即打斗镜头数和接吻镜头数。

除此之外，我们也知道每个电影的所属类型，即分类标签。用肉眼粗略地观察，接吻镜头多的，是爱情片。打斗镜头多的，是动作片。

![jupyter](https://i.loli.net/2021/06/15/Dsd65raSmEypA8B.png)

那么，我们就要通过KNN进行训练，然后随机给出一组数据：打斗镜头数和接吻镜头数，从而帮助我们进行判断出属于哪种类型的影片。

首先介绍一下我们接下来使用的一些参数

dataSet - 用于训练的数据(训练集)

labes - 分类标签

test - 用于分类的数据(测试集)

k - kNN算法参数,选择距离最小的k个点

**准备并创建数据集**

In [3]:
import numpy as np
import operator
#四组二维特征
dataSet = np.array([[1,101],[5,89],[108,5],[115,8]])
#四组特征的标签
labels = ['爱情片','爱情片','动作片','动作片']

In [4]:
#打印数据集    
print("dataSet :\n",dataSet)
print("labels:\n",labels)

dataSet :
 [[  1 101]
 [  5  89]
 [108   5]
 [115   8]]
labels:
 ['爱情片', '爱情片', '动作片', '动作片']


**根据两点距离公式，计算距离，选择距离最小的前k个点，并返回分类结果。**

比如说，我们就去看看打斗镜头数为101和接吻镜头数为20的影片，我们目测它很大的几率是动作片，那KNN会给我们判断出什么类型。我们代码实现一下吧

In [5]:
test=[101,20]
k=3

In [6]:
#numpy函数shape[0]返回dataSet的行数
dataSetSize = dataSet.shape[0]
print(dataSetSize)

4


In [7]:
#在列向量方向上重复test共1次(横向)，行向量方向上重复test共dataSetSize次(纵向)
diffMat = np.tile(test, (dataSetSize, 1)) - dataSet
print(diffMat)

[[100 -81]
 [ 96 -69]
 [ -7  15]
 [-14  12]]


In [8]:
#二维特征相减后平方
sqDiffMat = diffMat**2
print(sqDiffMat)

[[10000  6561]
 [ 9216  4761]
 [   49   225]
 [  196   144]]


In [9]:
#sum()所有元素相加，sum(0)列相加，sum(1)行相加
sqDistances = sqDiffMat.sum(axis=1)
#开方，计算出距离
distances = sqDistances**0.5
print(distances)

[128.68954892 118.22436297  16.55294536  18.43908891]


In [10]:
#返回distances中元素从小到大排序后的索引值
sortedDistIndices = distances.argsort()
print(sortedDistIndices)

[2 3 1 0]


In [11]:
#定一个记录类别次数的字典
classCount = {}
for i in range(k):
    #取出前k个元素的类别
     voteIlabel = labels[sortedDistIndices[i]]
    #dict.get(key,default=None),字典的get()方法,返回指定键的值,如果值不在字典中返回默认值。
    #计算类别次数
     classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1

In [12]:
#reverse降序排序字典
sortedClassCount = sorted(classCount.items(),key=operator.itemgetter(1),reverse=True)
print(sortedClassCount)

[('动作片', 2), ('爱情片', 1)]


In [13]:
#返回次数最多的类别,即所要分类的类别
print(sortedClassCount[0][0])

动作片


## 编程要求

In [ ]:
import numpy as np
import operator

"""
函数说明:创建数据集

Parameters:
    无
Returns:
    group - 数据集
    labels - 分类标签

"""
def createDataSet():
    #四组二维特征
    group = np.array([[1,101],[5,89],[108,5],[115,8]])
    #四组特征的标签
    labels = ['爱情片','爱情片','动作片','动作片']
    return group, labels

"""
函数说明:kNN算法,分类器

Parameters:
    inX - 用于分类的数据(测试集)
    dataSet - 用于训练的数据(训练集)
    labes - 分类标签
    k - kNN算法参数,选择距离最小的k个点
Returns:
    sortedClassCount[0][0] - 分类结果

"""
def classify0(inX, dataSet, labels, k):
************** Begin **************



**************  END  **************

if __name__ == '__main__':
    #创建数据集
    group, labels = createDataSet()
    #测试集
    test = [200,320]
    #kNN分类
    test_class = classify0(test, group, labels, 3)
    #打印分类结果
    print(test_class)

## 参考答案

In [ ]:
def classify0(inX, dataSet, labels, k):
    #numpy函数shape[0]返回dataSet的行数
    dataSetSize = dataSet.shape[0]
    #在列向量方向上重复inX共1次(横向)，行向量方向上重复inX共dataSetSize次(纵向)
    diffMat = np.tile(inX, (dataSetSize, 1)) - dataSet
    #二维特征相减后平方
    sqDiffMat = diffMat**2
    #sum()所有元素相加，sum(0)列相加，sum(1)行相加
    sqDistances = sqDiffMat.sum(axis=1)
    #开方，计算出距离
    distances = sqDistances**0.5
    #返回distances中元素从小到大排序后的索引值
    sortedDistIndices = distances.argsort()
    #定一个记录类别次数的字典
    classCount = {}
    for i in range(k):
        #取出前k个元素的类别
        voteIlabel = labels[sortedDistIndices[i]]
        #dict.get(key,default=None),字典的get()方法,返回指定键的值,如果值不在字典中返回默认值。
        #计算类别次数
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    #reverse降序排序字典
    sortedClassCount = sorted(classCount.items(),key=operator.itemgetter(1),reverse=True)
    #返回次数最多的类别,即所要分类的类别
    return sortedClassCount[0][0]